version: 2
jobs:

  #go-1.9
  golang-1.9:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/medtune/go-utils
    steps:
      - checkout

      - run:
          name: installing pkg dependencies
          command: |
            go get -v -t -d ./...
      - run:
          name: test package
          command: |
            go test -v ./...

  #go-1.10
  golang-1.10:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/medtune/go-utils
    steps:
      - checkout

      - run:
          name: installing pkg dependencies
          command: |
            go get -v -t -d ./...
      - run:
          name: test package
          command: |
            go test -v ./...

  #go-latest
  golang-latest:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/medtune/go-utils
    steps:
      - checkout

      - run:
          name: installing pkg dependencies
          command: |
            go get -v -t -d ./...
      - run:
          name: test package
          command: |
            bash cover.sh
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - golang-1.9
      - golang-1.10
      - golang-latest